# Generated by Django 5.0.3 on 2024-03-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('shortcut', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('target', models.URLField(max_length=255, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
    ]
